
name: Metin2 Webhook Bot
on:
  schedule:
    - cron: '* * * * *'  # Her dakika çalışır (en düşük süre)
  workflow_dispatch:
jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
- name: Run webhook script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          STATUS_WEBHOOK_URL: ${{ secrets.STATUS_WEBHOOK_URL }}
        run: |
          node webhook-script.js
